# Usa una imagen oficial de PHP con las extensiones necesarias
FROM php:8.2-fpm

# Instala dependencias del sistema
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unzip \
    curl \
    git \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev && \ 
    docker-php-ext-install pdo pdo_pgsql mbstring exif pcntl bcmath gd && \
    rm -rf /var/lib/apt/lists/*



# Instala Node.js y npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Copia los archivos de Laravel al contenedor
WORKDIR /var/www
COPY . .

# Instala dependencias de Laravel
RUN composer install --no-dev --optimize-autoloader

# Instala dependencias de React y compila el frontend
WORKDIR /var/www/resources
RUN npm install && npm run build

# Cambia de nuevo al directorio raíz de Laravel
WORKDIR /var/www

# Da permisos correctos a storage y bootstrap/cache
RUN chmod -R 775 storage bootstrap/cache

# Expone el puerto del servidor
EXPOSE 9000

CMD ["php-fpm"]
